### ISSUE TITLE
about some details

### ISSUE THREAD

**Issue by foralliance** [qijiezhao/M2Det#22]
@qijiezhao  HI
非常感觉您的code，非常清晰易懂．
现有几个问题：
1. 本文提供的训练好的模型应该是**没有SFAM模块**的吧？？另外在configs文件夹中的多个参数文件中，都将sfam设为False．为什么这样设计？？

2. 网络中的＂Norm模块＂貌似没有参数初始化？？另外，为什么要单独对40尺度的特征图进行一个norm操作？？

3. 在TUM模块中，在layers模块中，前4个卷积操作都是kernel_size=(3, 3), stride=(2, 2), padding=(1, 1)，为什么第5个卷积是kernel_size=(3, 3), stride=(1, 1)．为什么这么设计？？
```
if not i == self.scales - 3:
    self.layers.add_module('{}'.format(len(self.layers)),BasicConv(self.planes, self.planes, 3, 2, 1))
 else:
    self.layers.add_module('{}'.format(len(self.layers)), BasicConv(self.planes, self.planes, 3, 1, 0))
```

4. 测试时，直接把原始图片resize到一个固定尺寸，这样**改变了原始图片的长宽比，也改变了图片内object的长宽比**．对结果是否有影响？？

5. 从code中，貌似并未看到multi-scale evaluation？？

6. paper中指出：The FFMv2 fuses the base feature and the largest output feature map of the previous Tum．从code来看＂the largest output feature map of the previous Tum＂其实指的就是＂尺度最大的那个特征＂，即40*40的特征．是这样吗？？

感谢！！

**Comment by qijiezhao** [comment]
Good question! 
Recently, we're preparing for some dues, sorry for the late answering.
1, Why SFAM False: Two points: (1)SFAM will slow down the training process. (2)SFAM is little tricky, sometimes positive while sometimes negative for the accuracy. For example, SFAM is beneficial for 320x320 size, but has no obvious improvement for 512x512 size. (we guess the main reason is training epochs). So, to avoid confusion, we set SFAM as False default. 
2, the lack of initiation of Norm layer has no effect to the final accuracy.(You can add it) 40x40 is the largest feature, we follow SSD to norm it due to that normal distribution is beneficial to stabilize the training process.
3, Why set the fifth Conv layer (stride:1x1, padding:0x0): To leave a larger feature map for the minimum one. This step can improve the localization accuracy of large objects.
4, Is there any negative influence when resizing original images to square shape for object detection: Very little, because we employ the same operation at training process.
5, Where is multi-scale evaluation: I am busy for other dues recently, this script will appear in next month.
6, "the largest output feature map" of "The FFMv2 fuses the base feature and the largest output feature map of the previous Tum" in original paper is 40x40? Yes

**Comment by foralliance** [comment]
@qijiezhao 
many many thanks!!!
